//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Net.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza_Ingridients
    {
        public int ID_Pizza_Ingrid { get; set; }
        public int ID_Pizza { get; set; }
        public int ID_Ingrid { get; set; }
    
        public virtual Ingridient Ingridient { get; set; }
        public virtual Pizza Pizza { get; set; }
    }
}
