//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Net.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaIngredient
    {
        public int IDPizzaIngredient { get; set; }
        public int IDPizza { get; set; }
        public int IDIngredient { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Pizza Pizza { get; set; }
    }
}
